################
### MONITORS ###
################

# https://wiki.hyprland.org/Configuring/Monitors/
# monitor = eDP-1,highres,auto,1

# Mirroring the first monitor on the second
# monitor = HDMI-A-1,highres,auto,1,mirror,eDP-1

monitor = DP-1, 2560x1440@180, 0x0, 1
monitor = HDMI-A-1, preferred, 2560x0, 1

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:HDMI-A-1, default:true
